### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: not valid ratio

### ISSUE THREAD

**Issue by lishoulin** [Kyson/AndroidGodEye#10]
FATAL EXCEPTION: RxComputationThreadPool-8
                                                                                  Process: cn.hikyson.android.godeye.sample, PID: 14665
                                                                                  io.reactivex.exceptions.OnErrorNotImplementedException: not valid ratio
                                                                                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
                                                                                      at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
                                                                                      at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
                                                                                      at io.reactivex.observers.SerializedObserver.onError(SerializedObserver.java:155)
                                                                                      at io.reactivex.internal.operators.observable.ObservableConcatMap$SourceObserver$InnerObserver.onError(ObservableConcatMap.java:254)
                                                                                      at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
                                                                                      at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
                                                                                      at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
                                                                                      at io.reactivex.internal.operators.observable.ObservableTimer$TimerObserver.run(ObservableTimer.java:67)
                                                                                      at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
                                                                                      at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                                   Caused by: cn.hikyson.godeye.core.internal.exception.GodEyeInvalidDataException: not valid ratio
                                                                                      at cn.hikyson.godeye.core.internal.modules.cpu.CpuEngine$3.apply(CpuEngine.java:70)
                                                                                      at cn.hikyson.godeye.core.internal.modules.cpu.CpuEngine$3.apply(CpuEngine.java:55)
                                                                                      at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
                                                                                      at io.reactivex.internal.operators.observable.ObservableTimer$TimerObserver.run(ObservableTimer.java:67) 
                                                                                      at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) 
                                                                                      at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) 
                                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by iHardWorking** [comment]
io.reactivex.exceptions.OnErrorNotImplementedException:Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
--
io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
 ......
Caused by: java.lang.NullPointerException:Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadlockDefaultThreadFilter.filter(DeadlockDefaultThreadFilter.java:11)
cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:48)
cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:43)
io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedObserver.emit(ObservableSampleTimed.java:116)
io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedNoLast.run(ObservableSampleTimed.java:138)
io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:273)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
java.lang.Thread.run(Thread.java:776)

**Comment by Kyson** [comment]
resolved at version1.7.4
thank you .
