### ISSUE TITLE
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference

### ISSUE THREAD

**Issue by xinglunyuan** [Kyson/AndroidGodEye#17]
io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:74)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(ObservableSubscribeOn.java:63)
	at io.reactivex.internal.observers.BasicFuseableObserver.onError(BasicFuseableObserver.java:100)
	at io.reactivex.internal.observers.BasicFuseableObserver.fail(BasicFuseableObserver.java:110)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:61)
	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
	at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedObserver.emit(ObservableSampleTimed.java:116)
	at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedNoLast.run(ObservableSampleTimed.java:138)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadlockDefaultThreadFilter.filter(DeadlockDefaultThreadFilter.java:11)
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:48)
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:43)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.ThreadGroup.getName()' on a null object reference
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadlockDefaultThreadFilter.filter(DeadlockDefaultThreadFilter.java:11)
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:48)
	at cn.hikyson.godeye.core.internal.modules.thread.deadlock.DeadLock$2.apply(DeadLock.java:43)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113)
	at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedObserver.emit(ObservableSampleTimed.java:116)
	at io.reactivex.internal.operators.observable.ObservableSampleTimed$SampleTimedNoLast.run(ObservableSampleTimed.java:138)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:278)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by xinglunyuan** [comment]
debug测试软件，经常出现上面的崩溃log

**Comment by Kyson** [comment]
@xinglunyuan 好的，我这几天会集中解决一下崩溃问题，谢谢反馈

**Comment by Kyson** [comment]
@xinglunyuan resolved at version 1.7.4
