### ISSUE TITLE
打开控件就崩溃

### ISSUE THREAD

**Issue by testerclub** [Kyson/AndroidGodEye#19]
app已经可以启动起来了，但是点击控件就崩溃，GodEyeMonitor.work(this);放到了application onCreate里，没有放到activity里，另外，浏览器查看性能数据，cpu无输出，heap、trafic、ram、pss都有输出，所有的监控项都install了，求指导，AndroidGodeye 1.7.4

02-11 16:57:54.037 19047-19047/com.testerclub.demo.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.testerclub.demo.test, PID: 19047
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.testerclub.demo.test/com.testerclub.core.base.PTWebViewActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5276)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                                        Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                                           at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:302)
                                                                           at android.app.Activity.requestWindowFeature(Activity.java:3656)
                                                                           at com.testerclub.TC.h5.activity.TCWebViewActivity.initView(TCWebViewActivity.java:46)
                                                                           at com.testerclub.TC.h5.activity.TCWebViewActivity.onCreate(TCWebViewActivity.java:41)
                                                                           at com.testerclub.core.base.BaseOfflineHybridActivity.onCreate(BaseOfflineHybridActivity.java:84)
                                                                           at com.testerclub.core.base.PTWebViewActivity.onCreate(PTWebViewActivity.java:25)
                                                                           at android.app.Activity.performCreate(Activity.java:6041)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2285)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394) 
                                                                           at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:135) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5276) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by Kyson** [comment]
这个crash好像不是androidgodeye里抛出的异常。
cpu如果没有值的话可能和机型有关，麻烦你把机型和操作系统版本告知我一下，多谢。

**Comment by testerclub** [comment]
异常是我的app抛出来的，但是在引入这个性能测试工程前没这个问题，cpu没数据的问题，后来重新连接监控端口就出来了，多谢

**Comment by testerclub** [comment]
引入工程后，点击任何控件都会蹦

**Comment by Kyson** [comment]
你看下你的TCWebViewActivity是不是在setcontentview之后调用了requestwindowfeature之类的方法。
总之你贴给我的错误堆栈和godeye没关系
如果还是不知道原因，方便的话把demo项目发给我看下

**Comment by testerclub** [comment]
GodEye.instance().install和GodEyeMonitor.work都是在application oncreat中调用的，但是在launcher和其他好几个activity里面都有setContentView，能把GodEye.instance().install和GodEyeMonitor.work都放到launcher里面调用么

**Comment by testerclub** [comment]
//    compile 'cn.hikyson.godeye:godeye-core:1.7.4'
//    debugImplementation 'cn.hikyson.godeye:godeye-monitor:1.7.4'
//    releaseImplementation 'cn.hikyson.godeye:godeye-monitor-no-op:1.7.4'
//    compile 'cn.hikyson.godeye:godeye-toolbox:1.7.4'

**Comment by devinhu** [comment]
/Users/devin/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/ba3db2beedc56ec8502ea9b29265574f/res/values-v26/values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/devin/workspace/pabank/PABankAndroid/source/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by devinhu** [comment]
集成报下吗这个错误
/Users/devin/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/ba3db2beedc56ec8502ea9b29265574f/res/values-v26/values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
Error:resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
/Users/devin/workspace/pabank/PABankAndroid/source/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details

**Comment by Kyson** [comment]
@devinhu 可能是v7包的版本不一致，你依赖的时候可以把我的appcompat-v7包 exclude掉，换成你的v7包

**Comment by Kyson** [comment]
@testerclub 不是很理解你的需求，把GodEye.instance().install和GodEyeMonitor.work都放到launcher里面调用有什么作用吗？

**Comment by Kyson** [comment]
@testerclub @devinhu 时间太久close了
