### ISSUE TITLE
java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by JesseWo** [Kyson/AndroidGodEye#31]
App启动几分钟后 crash, 启动后没进行任何交互
```
java.lang.ArithmeticException: divide by zero
        at cn.hikyson.godeye.core.internal.modules.fps.FpsEngine$3$1$1.doFrame(FpsEngine.java:78)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:883)
        at android.view.Choreographer.doCallbacks(Choreographer.java:697)
        at android.view.Choreographer.doFrame(Choreographer.java:630)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:871)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6338)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by yingguangchi** [comment]
我这也碰上过这种情况

**Comment by Kyson** [comment]
ok，这里有问题，我做下判断吧

**Comment by Kyson** [comment]
@JesseWo @yingguangchi fps新版本已经重构，再观察..
