### ISSUE TITLE
我的android设备是机顶盒，没电池，直接插电源的

### ISSUE THREAD

**Issue by ren93** [Kyson/AndroidGodEye#32]
java.lang.NullPointerException: Attempt to invoke virtual method 'io.reactivex.Observable cn.hikyson.godeye.core.internal.ProduceableSubject.subject()' on a null object reference
        at cn.hikyson.godeye.monitor.driver.Watcher.observeAll(Watcher.java:69)
        at cn.hikyson.godeye.monitor.GodEyeMonitor.work(GodEyeMonitor.java:82)
        at cn.hikyson.godeye.monitor.GodEyeMonitor.work(GodEyeMonitor.java:43)

**Comment by renjianan** [comment]
我的android设备是机顶盒，没电池，直接插电源的

**Comment by Kyson** [comment]
我看下先，多谢反馈
