### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference

### ISSUE THREAD

**Issue by xuduo** [Kyson/AndroidGodEye#73]
Got this crash, doesn't always occur.
I use multiple process in my app. One for push for example. 

java.lang.RuntimeException: Unable to start service cn.hikyson.godeye.core.internal.notification.LocalNotificationListenerService@b7afb04 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3922)
	at android.app.ActivityThread.access$1700(ActivityThread.java:240)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1828)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7094)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getAction()' on a null object reference
	at cn.hikyson.godeye.core.internal.notification.LocalNotificationListenerService.onStartCommand(LocalNotificationListenerService.java:45)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3903)
	... 8 more

**Comment by xuduo** [comment]
When my app starts

**Comment by Kyson** [comment]
Fixed in version 3.4.3.
