### ISSUE TITLE
Execution failed for task ':app:transformClassesWithMethodCanaryTransformForDebug'.

### ISSUE THREAD

**Issue by ylc88** [Kyson/AndroidGodEye#80]
hello

use methodCanary build throw 

Caused by: java.lang.IllegalArgumentException: Invalid opcode 169
	at org.objectweb.asm.commons.AdviceAdapter.visitVarInsn(AdviceAdapter.java:355)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2174)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at cn.hikyson.methodcanary.plugin.TransformHandler.handleJarInputs(TransformHandler.groovy:109)
	at cn.hikyson.methodcanary.plugin.TransformHandler$_handle_closure1$_closure4.doCall(TransformHandler.groovy:50)
	at cn.hikyson.methodcanary.plugin.TransformHandler$_handle_closure1.doCall(TransformHandler.groovy:49)
	at cn.hikyson.methodcanary.plugin.TransformHandler.handle(TransformHandler.groovy:45)
	at cn.hikyson.methodcanary.plugin.TransformHandler$handle.call(Unknown Source)
	at cn.hikyson.methodcanary.plugin.MethodCanaryTransform.transform(MethodCanaryTransform.groovy:42)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:247)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:106)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:242)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)

**Comment by Kyson** [comment]
Can you provide the version of AndroidGodEye?

**Comment by ylc88** [comment]
> Can you provide the version of AndroidGodEye?

thank you for your reply
AndroidGodEye version：3.4.3
methodcanary plugin: 0.15.5

Android studio version：4.1.2
gradle: gradle-5.6.4-all
Only methodcanary reports errors, others can be used normally, thank you

**Comment by Kyson** [comment]
This may be due to low version of asm, i will fix it recently

**Comment by Kyson** [comment]
You can downgrade AGP for now

**Comment by ylc88** [comment]
> You can downgrade AGP for now

ok, thank you
