### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Invalid opcode 169

### ISSUE THREAD

**Issue by taoliuh** [Kyson/AndroidGodEye#81]
Caused by: java.lang.IllegalArgumentException: Invalid opcode 169
at org.objectweb.asm.commons.AdviceAdapter.visitVarInsn(AdviceAdapter.java:355)
at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2174)
at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1283)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
at cn.hikyson.methodcanary.plugin.TransformHandler.handleJarInputs(TransformHandler.groovy:109)
at cn.hikyson.methodcanary.plugin.TransformHandler$_handle_closure1$_closure4.doCall(TransformHandler.groovy:50)
at cn.hikyson.methodcanary.plugin.TransformHandler$_handle_closure1.doCall(TransformHandler.groovy:49)
at cn.hikyson.methodcanary.plugin.TransformHandler.handle(TransformHandler.groovy:45)
at cn.hikyson.methodcanary.plugin.TransformHandler$handle.call(Unknown Source)
at cn.hikyson.methodcanary.plugin.MethodCanaryTransform.transform(MethodCanaryTransform.groovy:42)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:284)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:247)
at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:106)
at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:242)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)

I got this error when 高德 map is integrated. I want to ignore 高德 map package when gradle plugin doing scan work. But I cannot find groovy plugin in this project. Can you provide source code of this plugin called "cn.hikyson.methodcanary:plugin:0.15.5"

**Comment by Kyson** [comment]
@taoliuh Plugin Source Code is in [https://github.com/Kyson/MethodCanary](https://github.com/Kyson/MethodCanary)

It is asm version conflict with 高德sdk.
