### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Aracoix** [Kyson/AndroidGodEye#85]
java.lang.NullPointerException: Null is not a valid element
        at io.reactivex.internal.queue.SpscLinkedArrayQueue.offer(SpscLinkedArrayQueue.java:69)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onNext(ObservableObserveOn.java:117)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.subjects.ReplaySubject$UnboundedReplayBuffer.replay(ReplaySubject.java:770)
        at io.reactivex.subjects.ReplaySubject.onNext(ReplaySubject.java:352)
        at cn.hikyson.godeye.core.internal.ProduceableSubject.produce(ProduceableSubject.java:23)
        at cn.hikyson.godeye.core.internal.modules.network.Network.produce(Network.java:57)
        at cn.hikyson.godeye.core.GodEyeHelper.onNetworkEnd(GodEyeHelper.java:88)
        at cn.hikyson.android.godeye.okhttp.OkNetworkEventListener.callEnd(OkNetworkEventListener.java:176)
        at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:364)
        at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:212)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Kyson** [comment]
Check whether okhttp's response is null
